artifacts_root: artifacts

data_ingestion_gdrive:
  root_dir: artifacts/data_ingestion/gdrive
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: artifacts/data_ingestion/gdrive/data.zip
  extracted_dir: artifacts/data_ingestion/gdrive/extraction

data_ingestion_kaggle:
  root_dir: artifacts/data_ingestion/kaggle
  source_URL: https://www.kaggle.com/datasets/nazmul0087/ct-kidney-dataset-normal-cyst-tumor-and-stone/
  local_data_file: artifacts/data_ingestion/kaggle/data
  extracted_dir: artifacts/data_ingestion/kaggle/extraction
